version: "3.4"
services:
 health-insurance:
   image: node:alpine
   container_name: health-insurance
   entrypoint: /bin/sh
   ports:
     - 9053:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./vue-app
       target: /srv/app
   tty: true
